version: "3"

services:
    autogoal:
        image: "sestevez/autogoal"
        build: "."
        command: "pipenv run python"
        volumes:
            - "./:/autogoal"

    test:
        image: "sestevez/autogoal"
        command: "make test"
        volumes:
            - "./:/autogoal"
