version: "3"

services:
  autogoal-tester:
    container_name: autogoal-tester-${PYTHON_VERSION}
    image: docker.pkg.github.com/sestevez/autogoal/autogoal:${PYTHON_VERSION}
    build:
      context: "."
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - "./:/code"
      - "./autogoal:/usr/local/lib/python3.6/site-packages/autogoal"
    command: ["jupyter", "lab", "--allow-root", "--NotebookApp.password=", "--NotebookApp.token=", "--ip=0.0.0.0"]
    network_mode: host
