version: "3"

services:
    autogoal:
        image: "sestevez/autogoal"
        build: "."
        entrypoint: "pipenv run"
        volumes:
            - "./:/autogoal"
            - "./.venv/:/autogoal/.venv"
        environment:
            PIPENV_VENV_IN_PROJECT: "1"
            XDG_CACHE_HOME: "/autogoal/.venv/.cache"
        command: "bash"
