version: "3"

services:
    autogoal:
        image: "sestevez/autogoal"
        build: "."
        volumes:
            - "./:/autogoal"
            - "./.venv:/autogoal/.venv"
            - "~/nltk_data:/autogoal/.venv/nltk_data"
        environment:
            POETRY_VIRTUALENVS_PATH: /autogoal/.venv
        #     PIPENV_VENV_IN_PROJECT: "1"
        #     XDG_CACHE_HOME: "/autogoal/.venv/.cache"
        command: "pipenv shell"
