version: "3"

services:
    autogoal:
        image: "docker.pkg.github.com/sestevez/autogoal/autogoal:latest"
        build: "."
        volumes:
            - "./:/autogoal"
            # - "./.venv:/autogoal/.venv"
            - "~/nltk_data:/root/nltk_data"
        # environment:
        #     POETRY_VIRTUALENVS_PATH: /autogoal/.venv
        #     PIPENV_VENV_IN_PROJECT: "1"
        #     XDG_CACHE_HOME: "/autogoal/.venv/.cache"
        command: "poetry shell"
