site_name: AutoGOAL
repo_name: 'autogoal/autogoal'
repo_url: 'https://github.com/autogoal/autogoal'

theme:
    name: material
    feature:
        tabs: true

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - mkautodoc

nav:
    - Home: index.md
    - Dependencies: dependencies.md
    - Contributing: contributing.md
    - History: history.md

    - User Guide:
        - First steps: guide/index.md
        - Pre-designed pipelines: guide/predesigned.md
        - Defining the space:
            - Class-based API: guide/cfg.md
            - Graph-based API: guide/graph.md
            - Functional API: guide/functional.md


    - API:
        - AutoGOAL API: api/autogoal.md
        - Grammars: api/autogoal.grammar.md
        - Search: api/autogoal.search.md
        - Contrib:
            - Contrib API: api/autogoal.contrib.md
            - Sklearn: api/autogoal.contrib.sklearn.md
            - Keras: api/autogoal.contrib.keras.md
        - Datasets: api/autogoal.datasets.md
        - Utils: api/autogoal.utils.md

    - Examples:
        - Sklearn: examples/sklearn_simple_grammar.md
        - Keras: examples/keras_text_classifier.md
