site_name: AutoGOAL

theme:
    name: material
    feature:
        tabs: true

plugins:
    - search

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - markdown_include.include

nav:
    - Home: index.md
    - Dependencies: dependencies.md
    - Contributing: contributing.md
    - User Guide:
        - First steps: guide/index.md
        - Predefined pipelines: guide/predefined.md
        - Class-based API: guide/cfg.md
        - Graph-based API: guide/graph.md
        - Functional API: guide/functional.md
    - Examples:
        - Home: examples/index.md
        - EMNLP UCI datasets: examples/solving_uci_datasets.md
        - EMNLP HAHA 2019: examples/solving_haha_2019.md
        - EMNLP MEDDOCAN 2019: examples/solving_meddocan_2019.md
        - Sklearn integration: examples/sklearn_simple_grammar.md
        - Search strategies: examples/comparing_search_strategies.md
    - API:
        - autogoal:
          - Index: api/autogoal.md
          - optimize: api/autogoal.optimize.md
        - autogoal.contrib:
          - Index: api/autogoal.contrib.md
          - find_classes: api/autogoal.contrib.find_classes.md
        - autogoal.contrib.gensim:
          - Index: api/autogoal.contrib.gensim.md
          - find_classes: api/autogoal.contrib.gensim.find_classes.md
        - autogoal.contrib.keras:
          - Index: api/autogoal.contrib.keras.md
          - KerasClassifier: api/autogoal.contrib.keras.KerasClassifier.md
          - KerasImageClassifier: api/autogoal.contrib.keras.KerasImageClassifier.md
          - KerasImagePreprocessor: api/autogoal.contrib.keras.KerasImagePreprocessor.md
          - KerasNeuralNetwork: api/autogoal.contrib.keras.KerasNeuralNetwork.md
          - KerasSequenceClassifier: api/autogoal.contrib.keras.KerasSequenceClassifier.md
          - KerasSequenceTagger: api/autogoal.contrib.keras.KerasSequenceTagger.md
          - build_grammar: api/autogoal.contrib.keras.build_grammar.md
          - find_classes: api/autogoal.contrib.keras.find_classes.md
        - autogoal.contrib.nltk:
          - Index: api/autogoal.contrib.nltk.md
          - find_classes: api/autogoal.contrib.nltk.find_classes.md
        - autogoal.contrib.sklearn:
          - Index: api/autogoal.contrib.sklearn.md
          - find_classes: api/autogoal.contrib.sklearn.find_classes.md
        - autogoal.contrib.spacy:
          - Index: api/autogoal.contrib.spacy.md
          - SpacyNLP: api/autogoal.contrib.spacy.SpacyNLP.md
          - find_classes: api/autogoal.contrib.spacy.find_classes.md
        - autogoal.contrib.torch:
          - Index: api/autogoal.contrib.torch.md
          - BertEmbedding: api/autogoal.contrib.torch.BertEmbedding.md
          - BertTokenizeEmbedding: api/autogoal.contrib.torch.BertTokenizeEmbedding.md
          - find_classes: api/autogoal.contrib.torch.find_classes.md
        - autogoal.contrib.wikipedia:
          - Index: api/autogoal.contrib.wikipedia.md
          - WikipediaContainsWord: api/autogoal.contrib.wikipedia.WikipediaContainsWord.md
          - WikipediaContainsWordSpanish: api/autogoal.contrib.wikipedia.WikipediaContainsWordSpanish.md
          - WikipediaSummary: api/autogoal.contrib.wikipedia.WikipediaSummary.md
          - WikipediaSummarySpanish: api/autogoal.contrib.wikipedia.WikipediaSummarySpanish.md
          - find_classes: api/autogoal.contrib.wikipedia.find_classes.md
        - autogoal.datasets:
          - Index: api/autogoal.datasets.md
          - datapath: api/autogoal.datasets.datapath.md
          - download: api/autogoal.datasets.download.md
          - download_and_save: api/autogoal.datasets.download_and_save.md
          - pack: api/autogoal.datasets.pack.md
          - unpack: api/autogoal.datasets.unpack.md
        - autogoal.grammar:
          - Index: api/autogoal.grammar.md
          - Block: api/autogoal.grammar.Block.md
          - Boolean: api/autogoal.grammar.Boolean.md
          - Categorical: api/autogoal.grammar.Categorical.md
          - CfgInitializer: api/autogoal.grammar.CfgInitializer.md
          - ContextFreeGrammar: api/autogoal.grammar.ContextFreeGrammar.md
          - Continuous: api/autogoal.grammar.Continuous.md
          - Discrete: api/autogoal.grammar.Discrete.md
          - Empty: api/autogoal.grammar.Empty.md
          - Epsilon: api/autogoal.grammar.Epsilon.md
          - Grammar: api/autogoal.grammar.Grammar.md
          - Graph: api/autogoal.grammar.Graph.md
          - GraphGrammar: api/autogoal.grammar.GraphGrammar.md
          - GraphSpace: api/autogoal.grammar.GraphSpace.md
          - Path: api/autogoal.grammar.Path.md
          - Subset: api/autogoal.grammar.Subset.md
          - Symbol: api/autogoal.grammar.Symbol.md
          - Union: api/autogoal.grammar.Union.md
          - generate_cfg: api/autogoal.grammar.generate_cfg.md
        - autogoal.kb:
          - Index: api/autogoal.kb.md
          - CategoricalVector: api/autogoal.kb.CategoricalVector.md
          - Category: api/autogoal.kb.Category.md
          - Chunktag: api/autogoal.kb.Chunktag.md
          - ContinuousVector: api/autogoal.kb.ContinuousVector.md
          - DataType: api/autogoal.kb.DataType.md
          - DenseMatrix: api/autogoal.kb.DenseMatrix.md
          - DiscreteVector: api/autogoal.kb.DiscreteVector.md
          - Distinct: api/autogoal.kb.Distinct.md
          - Document: api/autogoal.kb.Document.md
          - Entity: api/autogoal.kb.Entity.md
          - Flags: api/autogoal.kb.Flags.md
          - Interface: api/autogoal.kb.Interface.md
          - List: api/autogoal.kb.List.md
          - Matrix: api/autogoal.kb.Matrix.md
          - MatrixContinuous: api/autogoal.kb.MatrixContinuous.md
          - MatrixContinuousDense: api/autogoal.kb.MatrixContinuousDense.md
          - MatrixContinuousSparse: api/autogoal.kb.MatrixContinuousSparse.md
          - Pipeline: api/autogoal.kb.Pipeline.md
          - PipelineBuilder: api/autogoal.kb.PipelineBuilder.md
          - Postag: api/autogoal.kb.Postag.md
          - Sentence: api/autogoal.kb.Sentence.md
          - Sentiment: api/autogoal.kb.Sentiment.md
          - SparseMatrix: api/autogoal.kb.SparseMatrix.md
          - Stem: api/autogoal.kb.Stem.md
          - Summary: api/autogoal.kb.Summary.md
          - Synset: api/autogoal.kb.Synset.md
          - Tensor3: api/autogoal.kb.Tensor3.md
          - Tensor4: api/autogoal.kb.Tensor4.md
          - Text: api/autogoal.kb.Text.md
          - Tuple: api/autogoal.kb.Tuple.md
          - Vector: api/autogoal.kb.Vector.md
          - Word: api/autogoal.kb.Word.md
          - algorithm: api/autogoal.kb.algorithm.md
          - build_composite_list: api/autogoal.kb.build_composite_list.md
          - build_composite_tuple: api/autogoal.kb.build_composite_tuple.md
          - build_pipeline_graph: api/autogoal.kb.build_pipeline_graph.md
          - build_pipelines: api/autogoal.kb.build_pipelines.md
          - conforms: api/autogoal.kb.conforms.md
          - draw_data_hierarchy: api/autogoal.kb.draw_data_hierarchy.md
          - infer_type: api/autogoal.kb.infer_type.md
          - make_list_wrapper: api/autogoal.kb.make_list_wrapper.md
        - autogoal.ml:
          - Index: api/autogoal.ml.md
          - AutoML: api/autogoal.ml.AutoML.md
          - DatasetFeatureExtractor: api/autogoal.ml.DatasetFeatureExtractor.md
          - DatasetFeatureLogger: api/autogoal.ml.DatasetFeatureLogger.md
          - LearnerMedia: api/autogoal.ml.LearnerMedia.md
        - autogoal.ml.metrics:
          - Index: api/autogoal.ml.metrics.md
          - accuracy: api/autogoal.ml.metrics.accuracy.md
          - find_metric: api/autogoal.ml.metrics.find_metric.md
          - register_metric: api/autogoal.ml.metrics.register_metric.md
        - autogoal.sampling:
          - Index: api/autogoal.sampling.md
          - DistributionParam: api/autogoal.sampling.DistributionParam.md
          - MeanDevParam: api/autogoal.sampling.MeanDevParam.md
          - ModelParam: api/autogoal.sampling.ModelParam.md
          - ModelSampler: api/autogoal.sampling.ModelSampler.md
          - ReplaySampler: api/autogoal.sampling.ReplaySampler.md
          - Sampler: api/autogoal.sampling.Sampler.md
          - UnormalizedWeightParam: api/autogoal.sampling.UnormalizedWeightParam.md
          - WeightParam: api/autogoal.sampling.WeightParam.md
          - best_indices: api/autogoal.sampling.best_indices.md
          - merge_updates: api/autogoal.sampling.merge_updates.md
          - update_model: api/autogoal.sampling.update_model.md
        - autogoal.search:
          - Index: api/autogoal.search.md
          - ConsoleLogger: api/autogoal.search.ConsoleLogger.md
          - Logger: api/autogoal.search.Logger.md
          - MemoryLogger: api/autogoal.search.MemoryLogger.md
          - PESearch: api/autogoal.search.PESearch.md
          - ProgressLogger: api/autogoal.search.ProgressLogger.md
          - RandomSearch: api/autogoal.search.RandomSearch.md
          - SearchAlgorithm: api/autogoal.search.SearchAlgorithm.md
          - SurrogateSearch: api/autogoal.search.SurrogateSearch.md
        - autogoal.utils:
          - Index: api/autogoal.utils.md
          - CacheManager: api/autogoal.utils.CacheManager.md
          - ResourceManager: api/autogoal.utils.ResourceManager.md
          - RestrictedWorker: api/autogoal.utils.RestrictedWorker.md
          - RestrictedWorkerByJoin: api/autogoal.utils.RestrictedWorkerByJoin.md
          - compute_class_weights: api/autogoal.utils.compute_class_weights.md
          - factory: api/autogoal.utils.factory.md
          - flatten: api/autogoal.utils.flatten.md
          - nice_repr: api/autogoal.utils.nice_repr.md
