site_name: AutoGOAL
repo_name: 'sestevez/autogoal'
repo_url: 'https://github.com/sestevez/autogoal'

theme:
    name: material
    feature:
        tabs: true

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - mkautodoc

nav:
    - Home: index.md
    - Dependencies: dependencies.md
    - Contributing: contributing.md
    - History: history.md

    - User Guide:
        - User Guide - Home: guide/index.md
        - Pipelines:
            - Pre-designed: guide/predesigned.md
            - Class-based: guide/cfg.md
            - Graph-based: guide/graph.md
            - Functional: guide/functional.md


    - API:
        - API - Home: api/index.md
        - Grammars: api/grammar.md
        - Search: api/search.md
        - Contrib:
            - Sklearn: api/sklearn.md
            - Keras: api/keras.md

    - Examples:
        - Sklearn: examples/sklearn_simple_grammar.md
        - Keras: examples/keras_text_classifier.md
