site_name: AutoGOAL

theme:
    name: material
    feature:
        tabs: true

plugins:
    - search
    # - pdf-export:
    #     combined: true

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - mkautodoc
    - markdown_include.include

nav:
    - Home: index.md
    - Dependencies: dependencies.md
    - Contributing: contributing.md

    - User Guide:
        - First steps: guide/index.md
        - Predefined pipelines: guide/predefined.md
        - Class-based API: guide/cfg.md
        - Graph-based API: guide/graph.md
        - Functional API: guide/functional.md

    - Examples:
        - Home: examples/index.md
        - ICML UCI datasets: examples/solving_uci_datasets.md
        - ICML HAHA 2019: examples/solving_haha_2019.md
        - ICML MEDDOCAN 2019: examples/solving_meddocan_2019.md
        - Sklearn integration: examples/sklearn_simple_grammar.md
        - Search strategies: examples/comparing_search_strategies.md

    - API:
        - AutoGOAL API: api/autogoal.md
        - Grammars: api/autogoal.grammar.md
        - Search: api/autogoal.search.md
        - Knowledge Base: api/autogoal.kb.md
        - AutoML: api/autogoal.ml.md
        - Contrib: api/autogoal.contrib.md
            # - Sklearn: api/autogoal.contrib.sklearn.md
            # - Keras: api/autogoal.contrib.keras.md
        - Datasets: api/autogoal.datasets.md
        - Utils: api/autogoal.utils.md
