site_name: AutoGOAL
site_url: https://autogoal.github.io
repo_url: https://github.com/autogoal/autogoal
edit_uri: edit/main/docs
google_analytics: 
  - UA-172957751-1
  - auto

theme:
    name: material
    logo: autogoal-logo.svg
    favicon: autogoal-logo-embedded.png
    feature:
        tabs: true
    palette:
        primary: deep orange
        accent: deep orange

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - markdown_include.include

nav:
    - Home: index.md
    - Dependencies: dependencies.md
    - Contributing: contributing.md
    - User Guide:
        - First steps: guide/index.md
        - Predefined pipelines: guide/predefined.md
        - Class-based API: guide/cfg.md
        - Graph-based API: guide/graph.md
        - Functional API: guide/functional.md
    - Examples:
        - Home: examples/index.md
        - Solving UCI datasets: examples/solving_uci_datasets.md
        - Solving HAHA 2019: examples/solving_haha_2019.md
        - Solving MEDDOCAN 2019: examples/solving_meddocan_2019.md
        - Sklearn integration: examples/sklearn_simple_grammar.md
        - Search strategies: examples/comparing_search_strategies.md
    - API:
        - autogoal:
          - Index: api/autogoal.md
          - optimize: api/autogoal.optimize.md
        - autogoal.contrib:
          - Index: api/autogoal.contrib.md
          - find_classes: api/autogoal.contrib.find_classes.md
        - autogoal.contrib.gensim:
          - Index: api/autogoal.contrib.gensim.md
          - FastTextEmbeddingSpanishSUC: api/autogoal.contrib.gensim.FastTextEmbeddingSpanishSUC.md
          - FastTextEmbeddingSpanishSWBC: api/autogoal.contrib.gensim.FastTextEmbeddingSpanishSWBC.md
          - GloveEmbeddingSpanishSWBC: api/autogoal.contrib.gensim.GloveEmbeddingSpanishSWBC.md
          - Word2VecEmbedding: api/autogoal.contrib.gensim.Word2VecEmbedding.md
          - Word2VecEmbeddingSpanish: api/autogoal.contrib.gensim.Word2VecEmbeddingSpanish.md
        - autogoal.contrib.keras:
          - Index: api/autogoal.contrib.keras.md
          - KerasClassifier: api/autogoal.contrib.keras.KerasClassifier.md
          - KerasImageClassifier: api/autogoal.contrib.keras.KerasImageClassifier.md
          - KerasImagePreprocessor: api/autogoal.contrib.keras.KerasImagePreprocessor.md
          - KerasSequenceClassifier: api/autogoal.contrib.keras.KerasSequenceClassifier.md
          - KerasSequenceTagger: api/autogoal.contrib.keras.KerasSequenceTagger.md
          - build_grammar: api/autogoal.contrib.keras.build_grammar.md
        - autogoal.contrib.nltk:
          - Index: api/autogoal.contrib.nltk.md
          - AffixTagger: api/autogoal.contrib.nltk.AffixTagger.md
          - BigramTagger: api/autogoal.contrib.nltk.BigramTagger.md
          - BlanklineTokenizer: api/autogoal.contrib.nltk.BlanklineTokenizer.md
          - Cistem: api/autogoal.contrib.nltk.Cistem.md
          - ClassifierBasedPOSTagger: api/autogoal.contrib.nltk.ClassifierBasedPOSTagger.md
          - ISRIStemmer: api/autogoal.contrib.nltk.ISRIStemmer.md
          - LancasterStemmer: api/autogoal.contrib.nltk.LancasterStemmer.md
          - LineTokenizer: api/autogoal.contrib.nltk.LineTokenizer.md
          - MWETokenizer: api/autogoal.contrib.nltk.MWETokenizer.md
          - PerceptronTagger: api/autogoal.contrib.nltk.PerceptronTagger.md
          - PorterStemmer: api/autogoal.contrib.nltk.PorterStemmer.md
          - PunktSentenceTokenizer: api/autogoal.contrib.nltk.PunktSentenceTokenizer.md
          - RSLPStemmer: api/autogoal.contrib.nltk.RSLPStemmer.md
          - SExprTokenizer: api/autogoal.contrib.nltk.SExprTokenizer.md
          - SnowballStemmer: api/autogoal.contrib.nltk.SnowballStemmer.md
          - SpaceTokenizer: api/autogoal.contrib.nltk.SpaceTokenizer.md
          - TabTokenizer: api/autogoal.contrib.nltk.TabTokenizer.md
          - TnT: api/autogoal.contrib.nltk.TnT.md
          - ToktokTokenizer: api/autogoal.contrib.nltk.ToktokTokenizer.md
          - TreebankWordTokenizer: api/autogoal.contrib.nltk.TreebankWordTokenizer.md
          - TrigramTagger: api/autogoal.contrib.nltk.TrigramTagger.md
          - TweetTokenizer: api/autogoal.contrib.nltk.TweetTokenizer.md
          - UnigramTagger: api/autogoal.contrib.nltk.UnigramTagger.md
          - WhitespaceTokenizer: api/autogoal.contrib.nltk.WhitespaceTokenizer.md
          - WordNetLemmatizer: api/autogoal.contrib.nltk.WordNetLemmatizer.md
          - WordPunctTokenizer: api/autogoal.contrib.nltk.WordPunctTokenizer.md
        - autogoal.contrib.regex:
          - Index: api/autogoal.contrib.regex.md
          - EmailRegex: api/autogoal.contrib.regex.EmailRegex.md
          - IPRegex: api/autogoal.contrib.regex.IPRegex.md
          - MACRegex: api/autogoal.contrib.regex.MACRegex.md
          - PhoneRegex: api/autogoal.contrib.regex.PhoneRegex.md
          - UrlRegex: api/autogoal.contrib.regex.UrlRegex.md
        - autogoal.contrib.sklearn:
          - Index: api/autogoal.contrib.sklearn.md
          - ARDRegression: api/autogoal.contrib.sklearn.ARDRegression.md
          - AffinityPropagation: api/autogoal.contrib.sklearn.AffinityPropagation.md
          - BayesianRidge: api/autogoal.contrib.sklearn.BayesianRidge.md
          - BernoulliNB: api/autogoal.contrib.sklearn.BernoulliNB.md
          - Birch: api/autogoal.contrib.sklearn.Birch.md
          - CategoricalNB: api/autogoal.contrib.sklearn.CategoricalNB.md
          - ComplementNB: api/autogoal.contrib.sklearn.ComplementNB.md
          - CountVectorizer: api/autogoal.contrib.sklearn.CountVectorizer.md
          - CountVectorizerNoTokenize: api/autogoal.contrib.sklearn.CountVectorizerNoTokenize.md
          - DecisionTreeClassifier: api/autogoal.contrib.sklearn.DecisionTreeClassifier.md
          - DecisionTreeRegressor: api/autogoal.contrib.sklearn.DecisionTreeRegressor.md
          - ElasticNet: api/autogoal.contrib.sklearn.ElasticNet.md
          - ExtraTreeClassifier: api/autogoal.contrib.sklearn.ExtraTreeClassifier.md
          - ExtraTreeRegressor: api/autogoal.contrib.sklearn.ExtraTreeRegressor.md
          - FactorAnalysis: api/autogoal.contrib.sklearn.FactorAnalysis.md
          - FastICA: api/autogoal.contrib.sklearn.FastICA.md
          - FeatureAgglomeration: api/autogoal.contrib.sklearn.FeatureAgglomeration.md
          - FlagsDenseVectorizer: api/autogoal.contrib.sklearn.FlagsDenseVectorizer.md
          - FlagsSparseVectorizer: api/autogoal.contrib.sklearn.FlagsSparseVectorizer.md
          - GaussianNB: api/autogoal.contrib.sklearn.GaussianNB.md
          - HashingVectorizer: api/autogoal.contrib.sklearn.HashingVectorizer.md
          - HuberRegressor: api/autogoal.contrib.sklearn.HuberRegressor.md
          - IncrementalPCA: api/autogoal.contrib.sklearn.IncrementalPCA.md
          - Isomap: api/autogoal.contrib.sklearn.Isomap.md
          - KBinsDiscretizer: api/autogoal.contrib.sklearn.KBinsDiscretizer.md
          - KMeans: api/autogoal.contrib.sklearn.KMeans.md
          - KNNImputer: api/autogoal.contrib.sklearn.KNNImputer.md
          - KNeighborsClassifier: api/autogoal.contrib.sklearn.KNeighborsClassifier.md
          - KNeighborsRegressor: api/autogoal.contrib.sklearn.KNeighborsRegressor.md
          - KNeighborsTransformer: api/autogoal.contrib.sklearn.KNeighborsTransformer.md
          - KernelCenterer: api/autogoal.contrib.sklearn.KernelCenterer.md
          - KernelPCA: api/autogoal.contrib.sklearn.KernelPCA.md
          - LabelBinarizer: api/autogoal.contrib.sklearn.LabelBinarizer.md
          - Lars: api/autogoal.contrib.sklearn.Lars.md
          - Lasso: api/autogoal.contrib.sklearn.Lasso.md
          - LassoLars: api/autogoal.contrib.sklearn.LassoLars.md
          - LassoLarsIC: api/autogoal.contrib.sklearn.LassoLarsIC.md
          - LatentDirichletAllocation: api/autogoal.contrib.sklearn.LatentDirichletAllocation.md
          - LinearRegression: api/autogoal.contrib.sklearn.LinearRegression.md
          - LinearSVC: api/autogoal.contrib.sklearn.LinearSVC.md
          - LinearSVR: api/autogoal.contrib.sklearn.LinearSVR.md
          - LocalOutlierFactor: api/autogoal.contrib.sklearn.LocalOutlierFactor.md
          - LocallyLinearEmbedding: api/autogoal.contrib.sklearn.LocallyLinearEmbedding.md
          - LogisticRegression: api/autogoal.contrib.sklearn.LogisticRegression.md
          - MeanShift: api/autogoal.contrib.sklearn.MeanShift.md
          - MinMaxScaler: api/autogoal.contrib.sklearn.MinMaxScaler.md
          - MiniBatchKMeans: api/autogoal.contrib.sklearn.MiniBatchKMeans.md
          - MiniBatchSparsePCA: api/autogoal.contrib.sklearn.MiniBatchSparsePCA.md
          - MultinomialNB: api/autogoal.contrib.sklearn.MultinomialNB.md
          - NMF: api/autogoal.contrib.sklearn.NMF.md
          - NearestCentroid: api/autogoal.contrib.sklearn.NearestCentroid.md
          - NuSVC: api/autogoal.contrib.sklearn.NuSVC.md
          - NuSVR: api/autogoal.contrib.sklearn.NuSVR.md
          - OneClassSVM: api/autogoal.contrib.sklearn.OneClassSVM.md
          - OneHotEncoder: api/autogoal.contrib.sklearn.OneHotEncoder.md
          - OrdinalEncoder: api/autogoal.contrib.sklearn.OrdinalEncoder.md
          - OrthogonalMatchingPursuit: api/autogoal.contrib.sklearn.OrthogonalMatchingPursuit.md
          - PCA: api/autogoal.contrib.sklearn.PCA.md
          - PassiveAggressiveClassifier: api/autogoal.contrib.sklearn.PassiveAggressiveClassifier.md
          - PassiveAggressiveRegressor: api/autogoal.contrib.sklearn.PassiveAggressiveRegressor.md
          - Perceptron: api/autogoal.contrib.sklearn.Perceptron.md
          - PowerTransformer: api/autogoal.contrib.sklearn.PowerTransformer.md
          - RadiusNeighborsRegressor: api/autogoal.contrib.sklearn.RadiusNeighborsRegressor.md
          - RadiusNeighborsTransformer: api/autogoal.contrib.sklearn.RadiusNeighborsTransformer.md
          - Ridge: api/autogoal.contrib.sklearn.Ridge.md
          - RidgeClassifier: api/autogoal.contrib.sklearn.RidgeClassifier.md
          - RobustScaler: api/autogoal.contrib.sklearn.RobustScaler.md
          - SGDClassifier: api/autogoal.contrib.sklearn.SGDClassifier.md
          - SGDRegressor: api/autogoal.contrib.sklearn.SGDRegressor.md
          - SVC: api/autogoal.contrib.sklearn.SVC.md
          - SVR: api/autogoal.contrib.sklearn.SVR.md
          - SparsePCA: api/autogoal.contrib.sklearn.SparsePCA.md
          - StandardScaler: api/autogoal.contrib.sklearn.StandardScaler.md
          - TfidfTransformer: api/autogoal.contrib.sklearn.TfidfTransformer.md
          - TfidfVectorizer: api/autogoal.contrib.sklearn.TfidfVectorizer.md
          - TheilSenRegressor: api/autogoal.contrib.sklearn.TheilSenRegressor.md
          - TruncatedSVD: api/autogoal.contrib.sklearn.TruncatedSVD.md
        - autogoal.contrib.spacy:
          - Index: api/autogoal.contrib.spacy.md
          - SpacyNLP: api/autogoal.contrib.spacy.SpacyNLP.md
        - autogoal.contrib.torch:
          - Index: api/autogoal.contrib.torch.md
          - BertEmbedding: api/autogoal.contrib.torch.BertEmbedding.md
          - BertTokenizeEmbedding: api/autogoal.contrib.torch.BertTokenizeEmbedding.md
        - autogoal.contrib.wikipedia:
          - Index: api/autogoal.contrib.wikipedia.md
          - WikipediaContainsWord: api/autogoal.contrib.wikipedia.WikipediaContainsWord.md
          - WikipediaContainsWordSpanish: api/autogoal.contrib.wikipedia.WikipediaContainsWordSpanish.md
          - WikipediaSummary: api/autogoal.contrib.wikipedia.WikipediaSummary.md
          - WikipediaSummarySpanish: api/autogoal.contrib.wikipedia.WikipediaSummarySpanish.md
        - autogoal.datasets:
          - Index: api/autogoal.datasets.md
          - datapath: api/autogoal.datasets.datapath.md
          - download: api/autogoal.datasets.download.md
          - download_and_save: api/autogoal.datasets.download_and_save.md
          - pack: api/autogoal.datasets.pack.md
          - unpack: api/autogoal.datasets.unpack.md
        - autogoal.grammar:
          - Index: api/autogoal.grammar.md
          - Block: api/autogoal.grammar.Block.md
          - Boolean: api/autogoal.grammar.Boolean.md
          - Categorical: api/autogoal.grammar.Categorical.md
          - CfgInitializer: api/autogoal.grammar.CfgInitializer.md
          - ContextFreeGrammar: api/autogoal.grammar.ContextFreeGrammar.md
          - Continuous: api/autogoal.grammar.Continuous.md
          - Discrete: api/autogoal.grammar.Discrete.md
          - Empty: api/autogoal.grammar.Empty.md
          - Epsilon: api/autogoal.grammar.Epsilon.md
          - Grammar: api/autogoal.grammar.Grammar.md
          - Graph: api/autogoal.grammar.Graph.md
          - GraphGrammar: api/autogoal.grammar.GraphGrammar.md
          - GraphSpace: api/autogoal.grammar.GraphSpace.md
          - Path: api/autogoal.grammar.Path.md
          - Subset: api/autogoal.grammar.Subset.md
          - Symbol: api/autogoal.grammar.Symbol.md
          - Union: api/autogoal.grammar.Union.md
          - generate_cfg: api/autogoal.grammar.generate_cfg.md
        - autogoal.kb:
          - Index: api/autogoal.kb.md
          - CategoricalVector: api/autogoal.kb.CategoricalVector.md
          - Category: api/autogoal.kb.Category.md
          - Chunktag: api/autogoal.kb.Chunktag.md
          - ContinuousVector: api/autogoal.kb.ContinuousVector.md
          - DataType: api/autogoal.kb.DataType.md
          - DenseMatrix: api/autogoal.kb.DenseMatrix.md
          - DiscreteVector: api/autogoal.kb.DiscreteVector.md
          - Distinct: api/autogoal.kb.Distinct.md
          - Document: api/autogoal.kb.Document.md
          - Entity: api/autogoal.kb.Entity.md
          - Flags: api/autogoal.kb.Flags.md
          - Interface: api/autogoal.kb.Interface.md
          - List: api/autogoal.kb.List.md
          - Matrix: api/autogoal.kb.Matrix.md
          - MatrixContinuous: api/autogoal.kb.MatrixContinuous.md
          - MatrixContinuousDense: api/autogoal.kb.MatrixContinuousDense.md
          - MatrixContinuousSparse: api/autogoal.kb.MatrixContinuousSparse.md
          - Pipeline: api/autogoal.kb.Pipeline.md
          - PipelineBuilder: api/autogoal.kb.PipelineBuilder.md
          - Postag: api/autogoal.kb.Postag.md
          - Sentence: api/autogoal.kb.Sentence.md
          - Sentiment: api/autogoal.kb.Sentiment.md
          - SparseMatrix: api/autogoal.kb.SparseMatrix.md
          - Stem: api/autogoal.kb.Stem.md
          - Summary: api/autogoal.kb.Summary.md
          - Synset: api/autogoal.kb.Synset.md
          - Tensor3: api/autogoal.kb.Tensor3.md
          - Tensor4: api/autogoal.kb.Tensor4.md
          - Text: api/autogoal.kb.Text.md
          - Tuple: api/autogoal.kb.Tuple.md
          - Vector: api/autogoal.kb.Vector.md
          - Word: api/autogoal.kb.Word.md
          - algorithm: api/autogoal.kb.algorithm.md
          - build_composite_list: api/autogoal.kb.build_composite_list.md
          - build_composite_tuple: api/autogoal.kb.build_composite_tuple.md
          - build_pipeline_graph: api/autogoal.kb.build_pipeline_graph.md
          - build_pipelines: api/autogoal.kb.build_pipelines.md
          - conforms: api/autogoal.kb.conforms.md
          - draw_data_hierarchy: api/autogoal.kb.draw_data_hierarchy.md
          - infer_type: api/autogoal.kb.infer_type.md
          - make_list_wrapper: api/autogoal.kb.make_list_wrapper.md
        - autogoal.ml:
          - Index: api/autogoal.ml.md
          - AutoML: api/autogoal.ml.AutoML.md
          - DatasetFeatureExtractor: api/autogoal.ml.DatasetFeatureExtractor.md
          - DatasetFeatureLogger: api/autogoal.ml.DatasetFeatureLogger.md
          - LearnerMedia: api/autogoal.ml.LearnerMedia.md
        - autogoal.ml.metrics:
          - Index: api/autogoal.ml.metrics.md
          - accuracy: api/autogoal.ml.metrics.accuracy.md
          - find_metric: api/autogoal.ml.metrics.find_metric.md
          - register_metric: api/autogoal.ml.metrics.register_metric.md
        - autogoal.sampling:
          - Index: api/autogoal.sampling.md
          - DistributionParam: api/autogoal.sampling.DistributionParam.md
          - MeanDevParam: api/autogoal.sampling.MeanDevParam.md
          - ModelParam: api/autogoal.sampling.ModelParam.md
          - ModelSampler: api/autogoal.sampling.ModelSampler.md
          - ReplaySampler: api/autogoal.sampling.ReplaySampler.md
          - Sampler: api/autogoal.sampling.Sampler.md
          - UnormalizedWeightParam: api/autogoal.sampling.UnormalizedWeightParam.md
          - WeightParam: api/autogoal.sampling.WeightParam.md
          - best_indices: api/autogoal.sampling.best_indices.md
          - merge_updates: api/autogoal.sampling.merge_updates.md
          - update_model: api/autogoal.sampling.update_model.md
        - autogoal.search:
          - Index: api/autogoal.search.md
          - ConsoleLogger: api/autogoal.search.ConsoleLogger.md
          - Logger: api/autogoal.search.Logger.md
          - MemoryLogger: api/autogoal.search.MemoryLogger.md
          - PESearch: api/autogoal.search.PESearch.md
          - ProgressLogger: api/autogoal.search.ProgressLogger.md
          - RandomSearch: api/autogoal.search.RandomSearch.md
          - SearchAlgorithm: api/autogoal.search.SearchAlgorithm.md
          - SurrogateSearch: api/autogoal.search.SurrogateSearch.md
        - autogoal.utils:
          - Index: api/autogoal.utils.md
          - CacheManager: api/autogoal.utils.CacheManager.md
          - ResourceManager: api/autogoal.utils.ResourceManager.md
          - RestrictedWorker: api/autogoal.utils.RestrictedWorker.md
          - RestrictedWorkerByJoin: api/autogoal.utils.RestrictedWorkerByJoin.md
          - compute_class_weights: api/autogoal.utils.compute_class_weights.md
          - factory: api/autogoal.utils.factory.md
          - flatten: api/autogoal.utils.flatten.md
          - nice_repr: api/autogoal.utils.nice_repr.md
