[tool.poetry]
name = "autogoal"
version = "0.1.0"
description = "Automatic General-purpose Optimization for Algorithm Learning"
authors = ["Suilan Estevez-Velarde"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"
enlighten = "^1.4.0"
pyyaml = "^5.2"
owlready2 = "^0.22"
networkx = "^2.4"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
pylint = "^2.4.4"
codecov = "^2.0.15"
scikit-learn = "^0.22"
matplotlib = "^3.1.2"
nltk = "^3.4.5"
spacy = "^2.2.3"
gensim = "^3.8.1"
seqlearn = "^0.2"
cython = "^0.29.14"
sklearn_crfsuite = "^0.3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
