name: Update docs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64

      - name: Setup dependencies and build
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          poetry install --extras dev

      - name: Setup vendor libs
        run: |
          pip install https://github.com/apiad/illiterate/archive/refs/heads/master.zip

      - name: Build docs
        run: make docs-dev
        env:
          BUILD_ENVIRONMENT: development
  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: autogoal/autogoal.github.io
          publish_branch: master
          publish_dir: ./site
